local Settings = {}

Settings.Zones = {
	Zone1 = 100,
	Zone2 = 300,
	Zone3 = 1000,
	Zone4 = 1000,
	Zone5 = 1000,
	Zone6 = 1000,
	Zone7 = 1000,
	Zone8 = 1000,
	Zone9 = 1000,
	Zone10 = 1000,
	Zone11 = 1000,
	Zone12 = 1000,
	Zone13 = 1000,
	Zone14 = 1000,
	Zone15 = 1000,
	Zone16 = 1000,
	Zone17 = 1000,
	Zone18 = 1000,
	Zone19 = 1000,
	Zone20 = 1000,
	Zone21 = 1000,
}

Settings.ZoneSpawnRates = {
	Zone1 = 10,
	Zone2 = 300,
	Zone3 = 1000,
	Zone4 = 1000,
	Zone5 = 1000,
	Zone6 = 1000,
	Zone7 = 1000,
	Zone8 = 1000,
	Zone9 = 1000,
	Zone10 = 1000,
	Zone11 = 1000,
	Zone12 = 1000,
	Zone13 = 1000,
	Zone14 = 1000,
	Zone15 = 1000,
	Zone16 = 1000,
	Zone17 = 1000,
	Zone18 = 1000,
	Zone19 = 1000,
	Zone20 = 1000,
	Zone21 = 1000,
}

Settings.ZoneRarity = {
	Zone1 = { Common = 100 },
	Zone2 = {},
	Zone3 = {},
	Zone4 = {},
	Zone5 = {},
	Zone6 = {},
	Zone7 = {},
	Zone8 = {},
	Zone9 = {},
	Zone10 = {},
	Zone11 = {},
	Zone12 = {},
	Zone13 = {},
	Zone14 = {},
	Zone15 = {},
	Zone16 = {},
	Zone17 = {},
	Zone18 = {},
	Zone19 = {},
	Zone20 = {},
	Zone21 = {},
}

Settings.Power = {
	Base = 100,
	Multiplier = 1.0545,
	Offset = 10,
}

Settings.Speed = {
	Base = 100,
	Multiplier = 1.0545,
	Offset = 16,
}
Settings.Carry = {
	Base = 100,
	Multiplier = 1.0545,
	Offset = 1,
}

Settings.Plot = { Base = 1000, Multiplier = 4, Offset = 10 }

return Settings
